name: disk_cache
description: Library for persistent storage or caching.
version: 0.0.1+2
author:
homepage: https://github.com/rtmigo/fmap

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  file_errors: ^1.0.3
  #collection: ^1.15.0
  #  path: ../file_errors
  #file_errors:
  #  path: ../file_errors

dev_dependencies:
  xrandom: any

  test: ^1.5.1


