name: disk_cache
description: Bytes disk cache
version: 0.0.1+1
author:
homepage: https://github.com/rtmigo/dart_disk_cache

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  file_errors: ^1.0.3
  #collection: ^1.15.0
  #  path: ../file_errors
  #file_errors:
  #  path: ../file_errors

dev_dependencies:
  xrandom: any

  test: ^1.5.1


