name: fmap
description: A simple and efficient approach to caching or persistent blob storage. A Map-like object for accessing data stored on the filesystem.
version: 0.3.0+4
repository: https://github.com/rtmigo/fmap

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  file_errors: ^1.0.3
  path: ^1.8.0
  crypto: ^3.0.0
  meta: ^1.3.0

dev_dependencies:
  errno: ^1.4.1
  xrandom: any
  test: ^1.5.1
  pedantic: ^1.9.0